# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'concepto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DilogConceptos(object):
    def setupUi(self, DilogConceptos):
        DilogConceptos.setObjectName("DilogConceptos")
        DilogConceptos.resize(480, 221)
        DilogConceptos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_box = QtWidgets.QDialogButtonBox(DilogConceptos)
        self.btn_box.setGeometry(QtCore.QRect(300, 180, 160, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_box.setFont(font)
        self.btn_box.setStyleSheet("bottom: -100%;\n"
"  left: 0;\n"
"  width: 2px;\n"
"  height: 100%;\n"
"  background: rgb(6, 91, 103);\n"
"  color: rgb(255, 255, 255);")
        self.btn_box.setOrientation(QtCore.Qt.Horizontal)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_box.setObjectName("btn_box")
        self.lbl_departamento_frmC = QtWidgets.QLabel(DilogConceptos)
        self.lbl_departamento_frmC.setGeometry(QtCore.QRect(10, 48, 100, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_departamento_frmC.setFont(font)
        self.lbl_departamento_frmC.setStyleSheet("  font-size: 12px;\n"
"color: rgb(6, 91, 103);")
        self.lbl_departamento_frmC.setObjectName("lbl_departamento_frmC")
        self.cbb_departamento_frmC = QtWidgets.QComboBox(DilogConceptos)
        self.cbb_departamento_frmC.setGeometry(QtCore.QRect(10, 78, 460, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cbb_departamento_frmC.setFont(font)
        self.cbb_departamento_frmC.setStyleSheet(" color: rgb(255, 255, 255);\n"
"    background-color: rgb(6, 91, 103);")
        self.cbb_departamento_frmC.setObjectName("cbb_departamento_frmC")
        self.lbl_titulofrm = QtWidgets.QLabel(DilogConceptos)
        self.lbl_titulofrm.setGeometry(QtCore.QRect(0, 0, 480, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulofrm.setFont(font)
        self.lbl_titulofrm.setStyleSheet("  font-size: 18px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(6, 91, 103);")
        self.lbl_titulofrm.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulofrm.setObjectName("lbl_titulofrm")
        self.lbl_actividad_frmC = QtWidgets.QLabel(DilogConceptos)
        self.lbl_actividad_frmC.setGeometry(QtCore.QRect(10, 114, 72, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_actividad_frmC.setFont(font)
        self.lbl_actividad_frmC.setStyleSheet("font-size: 12px;\n"
"color: rgb(6, 91, 103);")
        self.lbl_actividad_frmC.setObjectName("lbl_actividad_frmC")
        self.lineEdit = QtWidgets.QLineEdit(DilogConceptos)
        self.lineEdit.setGeometry(QtCore.QRect(10, 140, 460, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("width: 100%;\n"
"  padding: 10px 0;\n"
"  font-size: 12px;\n"
"  color: rgb(6, 91, 103);\n"
"  border: none;\n"
"  outline: none;\n"
"  background: transparent;\n"
"border-bottom: 2px solid rgb(118, 118, 118) ;\n"
"color: rgb(6, 91, 103);")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(DilogConceptos)
        #self.btn_box.accepted.connect(DilogConceptos.accept) # type: ignore
        #self.btn_box.rejected.connect(DilogConceptos.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DilogConceptos)

    def retranslateUi(self, DilogConceptos):
        _translate = QtCore.QCoreApplication.translate
        DilogConceptos.setWindowTitle(_translate("DilogConceptos", ". . : : Conceptos : : . ."))
        self.lbl_departamento_frmC.setText(_translate("DilogConceptos", "DEPARTAMENTO"))
        self.lbl_titulofrm.setText(_translate("DilogConceptos", "AGREGAR ACTIVIDAD"))
        self.lbl_actividad_frmC.setText(_translate("DilogConceptos", "ACTIVIAD"))
        self.lineEdit.setPlaceholderText(_translate("DilogConceptos", "ACTIVIDAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DilogConceptos = QtWidgets.QDialog()
    ui = Ui_DilogConceptos()
    ui.setupUi(DilogConceptos)
    DilogConceptos.show()
    sys.exit(app.exec_())
