# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'concepto.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DilogConceptos(object):
    def setupUi(self, DilogConceptos):
        DilogConceptos.setObjectName("DilogConceptos")
        DilogConceptos.resize(400, 329)
        self.btn_box = QtWidgets.QDialogButtonBox(DilogConceptos)
        self.btn_box.setGeometry(QtCore.QRect(200, 280, 171, 32))
        self.btn_box.setStyleSheet("bottom: -100%;\n"
"  left: 0;\n"
"  width: 2px;\n"
"  height: 100%;\n"
"  background: linear-gradient(360deg, transparent, #03e9f4);")
        self.btn_box.setOrientation(QtCore.Qt.Horizontal)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_box.setObjectName("btn_box")
        self.label_3 = QtWidgets.QLabel(DilogConceptos)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 141, 41))
        self.label_3.setStyleSheet("  font-size: 16px;\n"
"color: rgb(84, 84, 84);")
        self.label_3.setObjectName("label_3")
        self.cb_departamento = QtWidgets.QComboBox(DilogConceptos)
        self.cb_departamento.setGeometry(QtCore.QRect(80, 110, 291, 31))
        self.cb_departamento.setStyleSheet(" color: inherit;\n"
"    background-color: var(--option-bg);")
        self.cb_departamento.setObjectName("cb_departamento")
        self.label_4 = QtWidgets.QLabel(DilogConceptos)
        self.label_4.setGeometry(QtCore.QRect(120, 10, 181, 41))
        self.label_4.setStyleSheet("  font-size: 16px;\n"
"color: rgb(84, 84, 84);")
        self.label_4.setObjectName("label_4")
        self.txt_concepto = QtWidgets.QTextEdit(DilogConceptos)
        self.txt_concepto.setGeometry(QtCore.QRect(20, 170, 351, 101))
        self.txt_concepto.setStyleSheet("width: 100%;\n"
"  padding: 10px 0;\n"
"  font-size: 16px;\n"
"  color: #fff;\n"
"  border: none;\n"
"  outline: none;\n"
"  background: transparent;\n"
"border: 2px solid rgb(118, 118, 118) ;\n"
"color: rgb(84, 84, 84);")
        self.txt_concepto.setObjectName("txt_concepto")

        self.retranslateUi(DilogConceptos)
        #self.btn_box.accepted.connect(DilogConceptos.accept) # type: ignore
        #self.btn_box.rejected.connect(DilogConceptos.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DilogConceptos)

    def retranslateUi(self, DilogConceptos):
        _translate = QtCore.QCoreApplication.translate
        DilogConceptos.setWindowTitle(_translate("DilogConceptos", "Conceptos"))
        self.label_3.setText(_translate("DilogConceptos", "DEPARTAMENTO"))
        self.label_4.setText(_translate("DilogConceptos", "AGREGAR CONCEPTO"))

'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DilogConceptos = QtWidgets.QDialog()
    ui = Ui_DilogConceptos()
    ui.setupUi(DilogConceptos)
    DilogConceptos.show()
    sys.exit(app.exec_())'''
