# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Viewformulario(object):
    def setupUi(self, Viewformulario):
        Viewformulario.setObjectName("Viewformulario")
        Viewformulario.resize(752, 684)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        Viewformulario.setFont(font)
        Viewformulario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Viewformulario)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_horasMinutos = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_horasMinutos.setGeometry(QtCore.QRect(400, 320, 221, 41))
        self.txt_horasMinutos.setStyleSheet("width: 100%;\n"
"  padding: 10px 0;\n"
"  font-size: 16px;\n"
"  color: #fff;\n"
"  border: none;\n"
"  outline: none;\n"
"  background: transparent;\n"
"border-bottom: 2px solid rgb(118, 118, 118) ;\n"
"color: rgb(84, 84, 84);")
        self.txt_horasMinutos.setText("")
        self.txt_horasMinutos.setObjectName("txt_horasMinutos")
        self.txt_op = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_op.setGeometry(QtCore.QRect(170, 80, 130, 36))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.txt_op.setFont(font)
        self.txt_op.setStyleSheet("width: 100%;\n"
"  padding: 10px 0;\n"
"  font-size: 16px;\n"
"  color: #fff;\n"
"  border: none;\n"
"  outline: none;\n"
"  background: transparent;\n"
"border-bottom: 2px solid rgb(118, 118, 118) ;\n"
"color: rgb(84, 84, 84);")
        self.txt_op.setText("")
        self.txt_op.setFrame(True)
        self.txt_op.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_op.setObjectName("txt_op")
        self.hfr__Frame1 = QtWidgets.QFrame(self.centralwidget)
        self.hfr__Frame1.setGeometry(QtCore.QRect(0, 0, 160, 741))
        self.hfr__Frame1.setStyleSheet("background-color: rgb(6, 91, 103);")
        self.hfr__Frame1.setObjectName("hfr__Frame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hfr__Frame1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_nombre = QtWidgets.QLabel(self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(170, 40, 561, 28))
        self.txt_nombre.setStyleSheet("  font-size: 16px;\n"
"color: rgb(6, 91, 103);\n"
"")
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cliente.setEnabled(False)
        self.txt_cliente.setGeometry(QtCore.QRect(300, 80, 440, 36))
        self.txt_cliente.setStyleSheet("width: 100%;\n"
"  padding: 10px 0;\n"
"  font-size: 16px;\n"
"  color: #fff;\n"
"  border: none;\n"
"  outline: none;\n"
"  background: transparent;\n"
"border-bottom: 2px solid rgb(118, 118, 118) ;\n"
"color: rgb(84, 84, 84);")
        self.txt_cliente.setText("")
        self.txt_cliente.setObjectName("txt_cliente")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 196, 138, 28))
        self.label_3.setStyleSheet("  font-size: 16px;\n"
"color: rgb(84, 84, 84);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 280, 91, 41))
        self.label_4.setStyleSheet("  font-size: 16px;\n"
"color: rgb(84, 84, 84);")
        self.label_4.setObjectName("label_4")
        self.cb_concepto = QtWidgets.QComboBox(self.centralwidget)
        self.cb_concepto.setGeometry(QtCore.QRect(270, 280, 241, 31))
        self.cb_concepto.setStyleSheet(" color: inherit;\n"
"    background-color: var(--option-bg);")
        self.cb_concepto.setObjectName("cb_concepto")
        self.btn_concepto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_concepto.setGeometry(QtCore.QRect(520, 280, 101, 31))
        self.btn_concepto.setStyleSheet(" background: linear-gradient(360deg,#03e9f4);")
        self.btn_concepto.setObjectName("btn_concepto")
        self.rb_horas = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_horas.setGeometry(QtCore.QRect(190, 320, 82, 31))
        self.rb_horas.setObjectName("rb_horas")
        self.rb_minutos = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_minutos.setGeometry(QtCore.QRect(300, 320, 82, 31))
        self.rb_minutos.setObjectName("rb_minutos")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(280, 610, 171, 41))
        self.btn_guardar.setStyleSheet(" background: linear-gradient(360deg,#03e9f4);\n"
"")
        self.btn_guardar.setObjectName("btn_guardar")
        self.btn_agregarActividad = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregarActividad.setGeometry(QtCore.QRect(310, 370, 141, 31))
        self.btn_agregarActividad.setStyleSheet("\n"
"  background: linear-gradient(360deg,#03e9f4);")
        self.btn_agregarActividad.setObjectName("btn_agregarActividad")
        self.btn_quitar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quitar.setGeometry(QtCore.QRect(520, 590, 111, 31))
        self.btn_quitar.setStyleSheet(" background: linear-gradient(360deg,#03e9f4);")
        self.btn_quitar.setObjectName("btn_quitar")
        self.cb_departamento = QtWidgets.QComboBox(self.centralwidget)
        self.cb_departamento.setGeometry(QtCore.QRect(170, 230, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_departamento.setFont(font)
        self.cb_departamento.setStyleSheet(" color: inherit;\n"
"    background-color: var(--option-bg);")
        self.cb_departamento.setObjectName("cb_departamento")
        self.dte_fechoy = QtWidgets.QDateEdit(self.centralwidget)
        self.dte_fechoy.setEnabled(False)
        self.dte_fechoy.setGeometry(QtCore.QRect(640, 3, 100, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dte_fechoy.setFont(font)
        self.dte_fechoy.setStyleSheet(" color: rgb(6, 91, 103);\n"
"   background: linear-gradient(360deg,#03e9f4);")
        self.dte_fechoy.setFrame(False)
        self.dte_fechoy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dte_fechoy.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dte_fechoy.setCalendarPopup(False)
        self.dte_fechoy.setDate(QtCore.QDate(2023, 10, 6))
        self.dte_fechoy.setObjectName("dte_fechoy")
        self.cb_productos = QtWidgets.QComboBox(self.centralwidget)
        self.cb_productos.setGeometry(QtCore.QRect(170, 160, 570, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_productos.setFont(font)
        self.cb_productos.setStyleSheet(" color: inherit;\n"
"    background-color: var(--option-bg);")
        self.cb_productos.setObjectName("cb_productos")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 130, 110, 28))
        self.label_5.setStyleSheet("  font-size: 16px;\n"
"color: rgb(84, 84, 84);")
        self.label_5.setObjectName("label_5")
        self.tabla_actividad = QtWidgets.QTableView(self.centralwidget)
        self.tabla_actividad.setEnabled(True)
        self.tabla_actividad.setGeometry(QtCore.QRect(170, 410, 571, 171))
        self.tabla_actividad.setStyleSheet("font-family: \"Lucida Sans Unicode\", \"Lucida Grande\", Sans-Serif;\n"
"    font-size: 12px;       width: 480px; text-align: left;    border-\n"
"\n"
"th {     font-size: 13px;     font-weight: normal;     padding: 8px;     background: #b9c9fe;\n"
"    border-top: 4px solid #aabcfe;    border-bottom: 1px solid #fff; color: #039; }\n"
"\n"
"td {    padding: 8px;     background: #e8edff;     border-bottom: 1px solid #fff;\n"
"    color: #669;    border-top: 1px solid transparent; }\n"
"\n"
"tr:hover td { background: #d0dafd; color: #339; }")
        self.tabla_actividad.setObjectName("tabla_actividad")
        Viewformulario.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Viewformulario)
        self.statusbar.setObjectName("statusbar")
        Viewformulario.setStatusBar(self.statusbar)

        self.retranslateUi(Viewformulario)
        QtCore.QMetaObject.connectSlotsByName(Viewformulario)

    def retranslateUi(self, Viewformulario):
        _translate = QtCore.QCoreApplication.translate
        Viewformulario.setWindowTitle(_translate("Viewformulario", "Actividades"))
        self.txt_horasMinutos.setPlaceholderText(_translate("Viewformulario", "HORAS O MINUTOS"))
        self.txt_op.setPlaceholderText(_translate("Viewformulario", "OP"))
        self.txt_nombre.setText(_translate("Viewformulario", "NOMBRE  COMPLETO"))
        self.txt_cliente.setPlaceholderText(_translate("Viewformulario", "CLIENTE"))
        self.label_3.setText(_translate("Viewformulario", "DEPARTAMENTO"))
        self.label_4.setText(_translate("Viewformulario", "CONCEPTO"))
        self.btn_concepto.setText(_translate("Viewformulario", "+ CONCEPTO"))
        self.rb_horas.setText(_translate("Viewformulario", "HORAS"))
        self.rb_minutos.setText(_translate("Viewformulario", "MINUTOS"))
        self.btn_guardar.setText(_translate("Viewformulario", "GUARDAR ACTIVIDADES"))
        self.btn_agregarActividad.setText(_translate("Viewformulario", "AGREGAR ACTIVIDAD"))
        self.btn_quitar.setText(_translate("Viewformulario", "QUITAR"))
        self.label_5.setText(_translate("Viewformulario", "PRODUCTOS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Viewformulario = QtWidgets.QMainWindow()
    ui = Ui_Viewformulario()
    ui.setupUi(Viewformulario)
    Viewformulario.show()
    sys.exit(app.exec_())
